name: tiki_style
description: Tiki Style Library
version: 0.0.20
homepage: https://mytiki.com
repository: https://github.com/tiki/style
issue_tracker: https://github.com/tiki/style/issues

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  lottie: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  assets:
    - lib/res/images/
    - lib/res/animation/
  fonts:
    - family: TikiIcons
      fonts:
        - asset: packages/tiki_style/res/icons/TikiIcons.ttf
    - family: Koara
      fonts:
        - asset: packages/tiki_style/res/fonts/Koara-Bold.ttf
          weight: 700
        - asset: packages/tiki_style/res/fonts/Koara-Regular.ttf
        - asset: packages/tiki_style/res/fonts/Koara-Light.ttf
          weight: 300
    - family: NunitoSans
      fonts:
        - asset: packages/tiki_style/res/fonts/NunitoSans-Black.ttf
          weight: 900
        - asset: packages/tiki_style/res/fonts/NunitoSans-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: packages/tiki_style/res/fonts/NunitoSans-ExtraBold.ttf
          weight: 800
        - asset: packages/tiki_style/res/fonts/NunitoSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: packages/tiki_style/res/fonts/NunitoSans-Bold.ttf
          weight: 700
        - asset: packages/tiki_style/res/fonts/NunitoSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: packages/tiki_style/res/fonts/NunitoSans-SemiBold.ttf
          weight: 600
        - asset: packages/tiki_style/res/fonts/NunitoSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: packages/tiki_style/res/fonts/NunitoSans-Regular.ttf
          weight: 400
        - asset: packages/tiki_style/res/fonts/NunitoSans-Italic.ttf
          weight: 400
          style: italic
        - asset: packages/tiki_style/res/fonts/NunitoSans-Light.ttf
          weight: 300
        - asset: packages/tiki_style/res/fonts/NunitoSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: packages/tiki_style/res/fonts/NunitoSans-ExtraLight.ttf
          weight: 200
        - asset: packages/tiki_style/res/fonts/NunitoSans-ExtraLightItalic.ttf
          weight: 200
          style: italic
    - family: Roboto
      fonts:
        - asset: packages/tiki_style/res/fonts/Roboto-Medium.ttf
          weight: 500
    - family: SegoeUI
      fonts:
        - asset: packages/tiki_style/res/fonts/Segoe-UI.ttf