name: tiki_style
description: Tiki Style Library
version: 0.0.7
homepage: https://mytiki.com
repository: https://github.com/tiki/style
issue_tracker: https://github.com/tiki/style/issues

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  lottie: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  assets:
    - lib/res/images/